### ISSUE TITLE
library not sorting by date added

### ISSUE THREAD

**Issue by chrisgilmore1** [mickstar/Zoo-For-Zotero#52]
HI,

Im using the latest version on android but when sorting my list early  g date added, it does not sort correctly. I'm not sure what it is using instead to order but it is consistent. All the other sorting functions work as intended. 

Chris

**Comment by mickstar** [comment]
Thanks for this, seems like a strange bug.

**Comment by rgfuller** [comment]
+1.  Sort by date (ascnd or descnd) no longer works.

**Comment by mickstar** [comment]
fixed 79b792549161589927e7a4c0016d965f59933cd1

**Comment by rgfuller** [comment]
Sort by Date Added is still not working for me.  I've cleared data and cache, and reinstalled.  Sorting is correct on zotero.com and desktop.

**Comment by mickstar** [comment]
Yes I haven't pushed it to google play yet, I have a few other changes that
aren't quite ready.

**Comment by conorokelly** [comment]
The new build, pushed today, fixed this bug for me on android 7.1. Thank you.
